CC = g++

COMMON_DIR					= Common
COM_BFWPROTOCOL_DIR			= $(COMMON_DIR)/Com_BFWProtocol
COM_FFWCOMMAND_DIR			= $(COMMON_DIR)/Com_FFWCommand
COM_FFWINTERFACE_DIR		= $(COMMON_DIR)/Com_FFWInterface
COM_HWCONTROL_DIR			= $(COMMON_DIR)/Com_HWControl
COM_VERSION_DIR				= $(COMMON_DIR)/Com_Version
EMUDEFINITION_DIR			= $(COMMON_DIR)/EmuDefinition
COMMONE2_DIR				= CommonE2
COME2_BFWPROTOCOL_DIR		= $(COMMONE2_DIR)/ComE2_BFWProtocol
COME2_FFWCOMMAND_DIR		= $(COMMONE2_DIR)/ComE2_FFWCommand
COME2_FFWINTERFACE_DIR		= $(COMMONE2_DIR)/ComE2_FFWInterface
COME2_VERSION_DIR			= $(COMMONE2_DIR)/ComE2_Version
COMMONRX_DIR				= CommonRX
COMRX_BFWPROTOCOL_DIR		= $(COMMONRX_DIR)/ComRX_BFWProtocol
COMRX_FFWCOMMAND_DIR		= $(COMMONRX_DIR)/ComRX_FFWCommand
COMRX_FFWINTERFACE_DIR		= $(COMMONRX_DIR)/ComRX_FFWInterface
COMRX_HWCONTROL_DIR			= $(COMMONRX_DIR)/ComRX_HWControl
COMRX_MCUCONTROL_DIR		= $(COMMONRX_DIR)/ComRX_MCUControl
COMRX_VERSION_DIR			= $(COMMONRX_DIR)/ComRX_Version
EMULATORINTERFACE_DIR 		= EmulatorInterface
MCU_DIR 					= Mcu
MCU_BFWPROTOCOL_DIR			= $(MCU_DIR)/MCU_BFWProtocol
MCU_ERRORCHECK_DIR 			= $(MCU_DIR)/Mcu_ErrorCheck
MCU_FFWCOMMAND_DIR 			= $(MCU_DIR)/Mcu_FFWCommand
MCU_FFWINTERFACE_DIR 		= $(MCU_DIR)/Mcu_FFWInterface
MCU_HWCONTROL_DIR 			= $(MCU_DIR)/Mcu_HWControl
MCU_MCUCONTROL_DIR 			= $(MCU_DIR)/Mcu_MCUControl
MCUDEFINITION_DIR 			= $(MCU_DIR)/McuDefinition
OTHER_DIR 					= Other
RFW_DIR 					= RFW
ASP_DIR 					= $(RFW_DIR)/ASP
ASP_BFWPROTOCOL_DIR 		= $(ASP_DIR)/ASP_BFWProtocol
ASP_HWCONTROL_DIR 			= $(ASP_DIR)/ASP_HWControl
ASP_RFWCOMMAND_DIR 			= $(ASP_DIR)/ASP_RFWCommand
ASP_RFWINTERFACE_DIR 		= $(ASP_DIR)/ASP_RFWInterface
ASP_VERSION_DIR 			= $(ASP_DIR)/ASP_Version
ASPRH_DIR 					= $(RFW_DIR)/ASPRH
ASPRH_BFWPROTOCOL_DIR 		= $(ASPRH_DIR)/ASPRH_BFWProtocol
ASPRH_HWCONTROL_DIR 		= $(ASPRH_DIR)/ASPRH_HWControl
ASPRH_RFWCOMMAND_DIR 		= $(ASPRH_DIR)/ASPRH_RFWCommand
ASPRH_RFWINTERFACE_DIR 		= $(ASPRH_DIR)/ASPRH_RFWInterface
ASPRL_DIR 					= $(RFW_DIR)/ASPRL
ASPRL_BFWPROTOCOL_DIR 		= $(ASPRL_DIR)/ASPRL_BFWProtocol
ASPRL_HWCONTROL_DIR 		= $(ASPRL_DIR)/ASPRL_HWControl
ASPRL_RFWCOMMAND_DIR 		= $(ASPRL_DIR)/ASPRL_RFWCommand
ASPRL_RFWINTERFACE_DIR 		= $(ASPRL_DIR)/ASPRL_RFWInterface
ASPRX_DIR 					= $(RFW_DIR)/ASPRX
ASPRX_BFWPROTOCOL_DIR 		= $(ASPRX_DIR)/ASPRX_BFWProtocol
ASPRX_HWCONTROL_DIR 		= $(ASPRX_DIR)/ASPRX_HWControl
ASPRX_RFWCOMMAND_DIR 		= $(ASPRX_DIR)/ASPRX_RFWCommand
ASPRX_RFWINTERFACE_DIR 		= $(ASPRX_DIR)/ASPRX_RFWInterface
RFW_COMMON_DIR 				= $(RFW_DIR)/Common
RFW_COM_RFWCOMMAND_DIR 		= $(RFW_COMMON_DIR)/Com_RFWCommand
RFW_COM_RFWINTERFACE_DIR 	= $(RFW_COMMON_DIR)/Com_RFWInterface
RFW_MCU_DIR 				= $(RFW_DIR)/Mcu
RFW_MCU_ERRORCHECK_DIR 		= $(RFW_MCU_DIR)/Mcu_ErrorCheck
RFW_MCU_MCUDEFINITION_DIR 	= $(RFW_MCU_DIR)/Mcu_McuDefinition
RFW_MCU_RFWINTERFACE_DIR 	= $(RFW_MCU_DIR)/Mcu_RFWInterface
RFW_OTHER_DIR 				= $(RFW_DIR)/Other


LIBUSB_LIB_DIR 				= /lib/x86_64-linux-gnu
LIBUSB_INCLUDE_DIR 			= /usr/include/libusb-1.0
COMMUNI_LIB_DIR 			= /usr/lib
COMMUNI_INCLUDE_DIR 		= /usr/include/communi
FFW_LIB_DIR 				= /usr/lib
FFW_INCLUDE_DIR 			= /usr/include/FFW
EXAMPLES_SRC_DIR 			= examples
BUILD_DIR 					= build

FFW_sub_dir = $(COMMON_DIR) $(COMMONE2_DIR) $(COMMONRX_DIR) $(EMULATORINTERFACE_DIR) $(MCU_DIR) $(OTHER_DIR)
Common_sub_dir = $(COM_BFWPROTOCOL_DIR) $(COM_FFWCOMMAND_DIR) $(COM_FFWINTERFACE_DIR) $(COM_HWCONTROL_DIR) $(COM_VERSION_DIR) $(EMUDEFINITION_DIR)
CommonE2_sub_dir = $(COME2_BFWPROTOCOL_DIR) $(COME2_FFWCOMMAND_DIR) $(COME2_FFWINTERFACE_DIR) $(COME2_VERSION_DIR)
CommonRX_sub_dir = $(COMRX_BFWPROTOCOL_DIR) $(COMRX_FFWCOMMAND_DIR) $(COMRX_FFWINTERFACE_DIR) $(COMRX_HWCONTROL_DIR) $(COMRX_MCUCONTROL_DIR) $(COMRX_VERSION_DIR)
Mcu_sub_dir = $(MCU_BFWPROTOCOL_DIR) $(MCU_ERRORCHECK_DIR) $(MCU_FFWCOMMAND_DIR) $(MCU_FFWINTERFACE_DIR) $(MCU_HWCONTROL_DIR) $(MCU_MCUCONTROL_DIR) $(MCUDEFINITION_DIR)

RFW_sub_dir = $(RFW_DIR) $(ASP_DIR) $(ASPRH_DIR) $(ASPRL_DIR) $(ASPRX_DIR) $(RFW_COMMON_DIR) $(RFW_MCU_DIR) $(RFW_OTHER_DIR)
ASP_sub_dir = $(ASP_BFWPROTOCOL_DIR) $(ASP_HWCONTROL_DIR) $(ASP_RFWCOMMAND_DIR) $(ASP_RFWINTERFACE_DIR) $(ASP_VERSION_DIR)
ASPRH_sub_dir = $(ASPRH_BFWPROTOCOL_DIR) $(ASPRH_HWCONTROL_DIR) $(ASPRH_RFWCOMMAND_DIR) $(ASPRH_RFWINTERFACE_DIR)
ASPRL_sub_dir = $(ASPRL_BFWPROTOCOL_DIR) $(ASPRL_HWCONTROL_DIR) $(ASPRL_RFWCOMMAND_DIR) $(ASPRL_RFWINTERFACE_DIR)
ASPRX_sub_dir = $(ASPRX_BFWPROTOCOL_DIR) $(ASPRX_HWCONTROL_DIR) $(ASPRX_RFWCOMMAND_DIR) $(ASPRX_RFWINTERFACE_DIR)
RFW_Common_sub_dir = $(RFW_COM_RFWCOMMAND_DIR) $(RFW_COM_RFWINTERFACE_DIR)
RFW_Mcu_sub_dir = $(RFW_MCU_ERRORCHECK_DIR) $(RFW_MCU_MCUDEFINITION_DIR) $(RFW_MCU_RFWINTERFACE_DIR)


src_dir     = $(FFW_sub_dir) $(Common_sub_dir) $(CommonE2_sub_dir) $(CommonRX_sub_dir) $(Mcu_sub_dir)
include_dir = $(FFW_sub_dir) $(Common_sub_dir) $(CommonE2_sub_dir) $(CommonRX_sub_dir) $(Mcu_sub_dir)  \
$(RFW_sub_dir) $(ASP_sub_dir) $(ASPRH_sub_dir) $(ASPRL_sub_dir) $(ASPRX_sub_dir) $(RFW_Common_sub_dir) $(RFW_Mcu_sub_dir)

obj_dir := $(patsubst %, $(BUILD_DIR)/%, $(src_dir) )

common_include_flags := $(patsubst %, -I%, $(Common_sub_dir))
commone2_include_flags := $(patsubst %, -I%, $(CommonE2_sub_dir))
commonrx_include_flags := $(patsubst %, -I%, $(CommonRX_sub_dir))
mcu_include_flags := $(patsubst %, -I%, $(Mcu_sub_dir))

rfw_asp_include_flags := $(patsubst %, -I%, $(ASP_sub_dir))
rfw_asprh_include_flags := $(patsubst %, -I%, $(ASPRH_sub_dir))
rfw_asprl_include_flags := $(patsubst %, -I%, $(ASPRL_sub_dir))
rfw_asprx_include_flags := $(patsubst %, -I%, $(ASPRX_sub_dir))
rfw_common_include_flags := $(patsubst %, -I%, $(RFW_Common_sub_dir))
rfw_mcu_include_flags := $(patsubst %, -I%, $(RFW_Mcu_sub_dir))

include_flags = $(common_include_flags) $(commone2_include_flags) $(commonrx_include_flags) -I$(EMULATORINTERFACE_DIR)  $(mcu_include_flags) -I$(OTHER_DIR)  $(rfw_asp_include_flags) $(rfw_asprx_include_flags) $(rfw_common_include_flags) -I$(RFW_OTHER_DIR)

sys_include_flags := $(patsubst -I%, -I$(FFW_INCLUDE_DIR)/%, $(include_flags) ) 
definitions = 
#-DFFWE20_EXPORTS -DFFWE100_API 

headers := $(foreach dir, $(include_dir) ,$(wildcard $(dir)/*.h))
sources := $(foreach dir, $(src_dir) ,$(wildcard $(dir)/*.cpp))
objects := $(patsubst %.cpp, $(BUILD_DIR)/%.o, $(sources))

test_sample = main init_ndeb_sample


all: create-objects-dir compile libffw.so

create-objects-dir:
	mkdir -p $(BUILD_DIR)
	@for dir in $(obj_dir); do \
		echo "mkdir -p" $$dir; \
		mkdir -p $$dir; \
	done

compile: create-objects-dir $(objects)

$(BUILD_DIR)/%.o: %.cpp
	@echo Compile $@
	$(CC) $< -fPIC -c $(include_flags) -o $@
	
libffw.so: $(objects)
	@echo Build $@.1.0
	$(CC) $^ -o $@.1.0 -shared -Wl,-soname,$@.1

create-include-dir: $(include_dir)
	sudo mkdir -p $(FFW_INCLUDE_DIR)
	@for dir in $^; do \
		{ echo "sudo mkdir -p" $(FFW_INCLUDE_DIR)/$$dir; \
		sudo mkdir -p $(FFW_INCLUDE_DIR)/$$dir; };  \
	done

copy-headers: $(headers)
	@echo Copy headers to $(FFW_INCLUDE_DIR)/ directory
	@for dir in $^; do \
		{ echo "sudo cp " $$dir" " $(FFW_INCLUDE_DIR)/$$dir; \
		sudo cp $$dir $(FFW_INCLUDE_DIR)/$$dir; };  \
	done

change-mode: $(headers)
	@for files in $^; do \
		{ echo "sudo chmod 644" $(FFW_INCLUDE_DIR)/$$files; \
		sudo chmod 644 $(FFW_INCLUDE_DIR)/$$files; };  \
	done

copy-lib: 
	@echo Install libffw.so
	sudo cp libffw.so.1.0 $(FFW_LIB_DIR)
	sudo ln -sf $(FFW_LIB_DIR)/libffw.so.1.0 $(FFW_LIB_DIR)/libffw.so.1
	sudo ln -sf $(FFW_LIB_DIR)/libffw.so.1.0 $(FFW_LIB_DIR)/libffw.so

install: copy-lib create-include-dir copy-headers change-mode

uninstall:
	@echo "Uninstall libffw.so.1.0"
	sudo rm -f $(FFW_LIB_DIR)/libffw.so
	sudo rm -f $(FFW_LIB_DIR)/libffw.so.1
	sudo rm -f $(FFW_LIB_DIR)/libffw.so.1.0
	sudo rm -rf $(FFW_INCLUDE_DIR)


#examples
examples: main init_ndeb_sample

examples-by-source: main-by-source init_ndeb_sample-by-source

main-by-source: compile $(EXAMPLES_SRC_DIR)/main.cpp 
	@echo "Build examples by source"
	mkdir -p $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)
	$(CC) $(EXAMPLES_SRC_DIR)/main.cpp -fPIC -c -I$(COMMUNI_INCLUDE_DIR) $(include_flags) $(definitions) -o $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/main.o
	$(CC) $(objects) $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/main.o -lcommuni -lusb-1.0 -o main

init_ndeb_sample-by-source: $(EXAMPLES_SRC_DIR)/init_ndeb_sample.cpp compile
	@echo "Build examples by source"
	mkdir -p $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)
	$(CC) $< -fPIC -c -I$(COMMUNI_INCLUDE_DIR) $(include_flags) $(definitions) -o $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/init_ndeb_sample.o
	$(CC) $(objects) $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/init_ndeb_sample.o -lcommuni -lusb-1.0 -o init_ndeb_sample


main:
	@echo Compile $@.o
	mkdir -p $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)
	$(CC) $(EXAMPLES_SRC_DIR)/$@.cpp -fPIC -c -I$(COMMUNI_INCLUDE_DIR) $(sys_include_flags) $(definitions) -o $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/$@.o
	@echo Build $@
	$(CC) $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/$@.o -lcommuni -lusb-1.0 -lffw  -o $@ 

init_ndeb_sample:
	@echo Compile $@.o
	mkdir -p $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)
	$(CC) $(EXAMPLES_SRC_DIR)/$@.cpp -fPIC -c -I$(COMMUNI_INCLUDE_DIR) $(sys_include_flags) $(definitions) -o $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/$@.o
	@echo Build $@
	$(CC) $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/$@.o -lcommuni -lusb-1.0 -lffw  -o $@ 

# Clean binary files
clean: 
	@for files in $(objects); do \
		{ echo "rm -f" $$files; \
		rm -f $$files; };  \
	done

clean-libffw:
	rm -f libffw.so.1.0

clean-examples:
	@for files in $(test_sample); do \
		{ echo "rm -f $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/"$$files".o" && rm -f $(BUILD_DIR)/$(EXAMPLES_SRC_DIR)/$$files.o; \
		echo "rm -f" $$files && rm -f $$files; };  \
	done

clean-all: clean clean-examples clean-libffw
